--RELACIONES


-- RELACION (PEDIDOS)

ALTER TABLE PEDIDO ADD FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente);

ALTER TABLE PEDIDO ADD FOREIGN KEY (id_metodo) REFERENCES METODO_PAGO(id_metodo);

ALTER TABLE PEDIDO ADD FOREIGN KEY (id_direccion) REFERENCES DIRECCION (id_direccion);



--RELACION DETALLE_PEDIDO


ALTER TABLE DETALLE_PEDIDO ADD FOREIGN KEY (id_pedido) REFERENCES PEDIDO(id_pedido);
ALTER TABLE DETALLE_PEDIDO ADD FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto);


--RELACION PRODUCTO

ALTER TABLE PRODUCTO ADD FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria);


--RELACION CARRITO

ALTER TABLE CARRITO ADD FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente);

--RELACION DETALLE_CARRITO

ALTER TABLE DETALLE_CARRITO ADD FOREIGN KEY (id_carrito) REFERENCES CARRITO(id_carrito);
ALTER TABLE DETALLE_CARRITO ADD FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto);

--RELACION INVENTARIO

ALTER TABLE INVENTARIO_PRODUCTO ADD FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto);


--RELACION DETALLE INVENTARIO

ALTER TABLE DETALLE_INVENTARIO ADD FOREIGN KEY (id_iventario) REFERENCES INVENTARIO_PRODUCTO(id_inventario);
ALTER TABLE DETALLE_INVENTARIO ADD FOREIGN KEY (id_direccion) REFERENCES DIRECCION(id_direccion);

--CORRECCIÓN DE CLIENTE

--ALTER TABLE cliente ADD COLUMN contrasena VARCHAR(15)



